# Generated by Django 5.2.6 on 2025-10-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='contenu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
